version: '3.4'

services:
  webapi:
    image: "rubix/webapi:${DOCKER_TAG:-latest}"
    container_name: "webapi"
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
      labels:
        - "build.number=${BUILD_NUMBER:-no-build-number}"
        - "build.commit=${GIT_COMMIT_HASH:-no-commit-hash}"
    environment:
      - LISTEN_PORT=5000
    ports:
      - "5000:5000"
    volumes:
     - ./webapi/app:/app
     - ./webapi/models:/models
